### ISSUE TITLE
csv import doesn't honour quoted text

### ISSUE THREAD

**Issue by BrisMark** [icsm-au/GDAy3.0#2]
When importing a csv file for conversion, quoted text using the " symbol is not treated as a single text field. Any commas that are quoted are still interpreted as column delimiters
[A Sites-outfile.csv](https://github.com/icsm-au/GDAy3.0/files/7050530/A.Sites-outfile.csv)
[A Sites-infile.csv](https://github.com/icsm-au/GDAy3.0/files/7050532/A.Sites-infile.csv)
.

**Comment by rogerfraser** [comment]
Closing this thanks to the work by @mattdocherty314
